version: '3.8'
services:
      custom-basic-java-app:
        image: ${IMAGE_NAME}
        ports:
          - 8081:8080
      postgres:
        image: postgres
        ports:
          - 5432:5432
        environment:
          POSTGRES_PASSWORD: def_pwd

